### PR TITLE
Added test queries

### PR DESCRIPTION
**Pull request by NathanAnto**

### CODE REVIEW

**Review by GDbateaux — APPROVED** [review]
SO GOOOOOOOOOOOOOOOOOD

**Comment by NathanAnto** [comment]
Qu'en penses tu Olivier ?

**Comment by GDbateaux** [comment]
@MadeInShineA STP REVIEW

**Review by MadeInShineA — APPROVED** [review]
Great pull request, thanks!

**Comment by NathanAnto** [comment]
Thank YOU !

**Pull request merged**
